# Generated by Django 5.2.6 on 2025-10-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_branch_alter_news_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="is_anonymous",
            field=models.BooleanField(
                default=False, help_text="If True, student identity is hidden"
            ),
        ),
    ]
